### PR TITLE
roundtrip boolean values

### PR DESCRIPTION
**Pull request by gugod**
HI @typester,

I wish to make boolean values roundtrip as nicely instead of turning them into 1/0. Therefore, corresponding Data::MessagePack boolean objects are created. Please take a look. Thanks.

### CODE REVIEW

**Comment by gugod** [comment]
Hi @typester,

I also change some travis-ci configuration. The `perl Makefile.PL | cpanm` is recognized as fail on travis-ci (probably because $? value), so I just hard-coded the dependency list in .travis.yml again.

**Comment by dolmen** [comment]
Why not use existing modules [JSON::PP::Boolean](https://metacpan.org/pod/JSON::PP#JSON::PP::is_bool) (which is in core) or [Types::Serialiser](https://metacpan.org/pod/Types::Serialiser)?

**Comment by gugod** [comment]
@dolmen because my main problem is that Data::MessagePack and Data::MessagePack::Stream does not work together due to this issue. What you mentioned make perfect sense, It's a just a goal better then mine.

**Comment by typester** [comment]
@gugod thanks! sorry about my too late merging :'p

**Comment by skaji** [comment]
We call `Data::MessagePack::true()` here
https://github.com/typester/Data-MessagePack-Stream/blob/74b5b0b302a1c764fac2d9444a8350af9fc068d5/lib/Data/MessagePack/Stream.xs#L58
but we don't require Data::MessagePack module.

As a result, the following script dies:
```perl
use Data::MessagePack::Stream;
my $stream = Data::MessagePack::Stream->new;
$stream->feed("\xC3"); # \xc3 == the serialization of "true"
$stream->next;
$stream->data;
```
```
❯ perl -Mblib test.pl
Undefined subroutine &Data::MessagePack::true called at test.pl line 5.
```

@typester 
I think we should:

* add `use Data::MessagePack` in lib/Data/MessagePack/Stream.pm
* add Data::MessagePack as a dependency in cpanfile

If you are OK, I will create a PR.

**Comment by typester** [comment]
@skaji  oh, good point. I didn't notice that. Thanks!

**Pull request merged**
